$(function(){
	$("#close-button").hover(
		function(){
			$(this).css({
				"background-position":"0 -16px",
			});
			$(this).parent().next().find(".close").css({
				"color":"#fff",
			});
		},
		function(){
			$(this).css({
				"background-position":"",
			});
			$(this).parent().next().find(".close").css({
				"color":"",
			});
		}
	);
	$(".close").hover(
		function(){
			$(this).css({
				"color":"#fff",
			});
			$(this).parent().prev().find("#close-button").css({
				"background-position":"0 -16px",
			});
		},
		function(){
			$(this).css({
				"color":"",
			});
			$(this).parent().prev().find("#close-button").css({
				"background-position":"",
			});
		}
	);
	$("#close-button").click(
		function(){
			$(this).parent().parent().css({
				"display":"none",
			});
			$(this).parent().parent().next("#container").css({
				"padding-top":"0",
			});
		}
	);
	$(".close").click(
		function(){
			$(this).parent().parent().css({
				"display":"none",
			});
			$(this).parent().parent().next("#container").css({
				"padding-top":"0",
			});
		}
	);
	$(".purchase").hover(
		function(){
			$(this).css({
				"color":"#fff",
			});
		},
		function(){
			$(this).css({
				"color":"",
			});
		}
	);
	$(".page-item").hover(

		function(){
			
			$(".page-item").removeClass("page-itemS");
			$(this).addClass("page-itemS");
		},
		function(){

		}
	);
});